; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ELIA"
#define MyAppVersion "0.9.3"
#define MyAppPublisher "</Sir_Alek>"
#define MyAppURL ""
#define MyAppExeName "ELIA.exe"
#define MyOutputDir "ELIA"
#define MySourceDir "dist\ELIA"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F3A2049F-1B90-4FB7-867B-923632826B8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UsePreviousAppDir=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#MyOutputDir}
OutputBaseFilename=ELIA_Setup
DiskSpanning=yes
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupIconFile=resources\logo_elia.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MySourceDir}\ELIA.exe"; DestDir: "{app}"; Flags: ignoreversion
; PyInstaller 6+ coloca dependencias en _internal\ (core\, frontend\, resources\, etc.).
Source: "{#MySourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Guía de usuario en la raíz de la app instalada (junto a ELIA.exe).
Source: "readme.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\_internal\resources\logo_elia.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\_internal\resources\logo_elia.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{cmd}"; Parameters: "/C taskkill /f /im ELIA.exe 2>nul"; Flags: runhidden

[Code]
function ParseVersionPart(const S: String; var Pos: Integer): Integer;
var
  Part: String;
begin
  Part := '';
  while (Pos <= Length(S)) and (S[Pos] >= '0') and (S[Pos] <= '9') do
  begin
    Part := Part + S[Pos];
    Pos := Pos + 1;
  end;
  if Part = '' then
    Result := 0
  else
    Result := StrToIntDef(Part, 0);
  if (Pos <= Length(S)) and (S[Pos] = '.') then
    Pos := Pos + 1;
end;

function CompareVersion(const A, B: String): Integer;
var
  I, MajA, MinA, PatA, MajB, MinB, PatB: Integer;
begin
  I := 1;
  MajA := ParseVersionPart(A, I);
  MinA := ParseVersionPart(A, I);
  PatA := ParseVersionPart(A, I);
  I := 1;
  MajB := ParseVersionPart(B, I);
  MinB := ParseVersionPart(B, I);
  PatB := ParseVersionPart(B, I);
  if (MajA < MajB) or ((MajA = MajB) and (MinA < MinB)) or
     ((MajA = MajB) and (MinA = MinB) and (PatA < PatB)) then
    Result := -1
  else if (MajA > MajB) or ((MajA = MajB) and (MinA > MinB)) or
          ((MajA = MajB) and (MinA = MinB) and (PatA > PatB)) then
    Result := 1
  else
    Result := 0;
end;

function ReadMaxVersionFromManifest: String;
var
  Path, Tag: String;
  Content: AnsiString;
  PStart, PEnd: Integer;
begin
  Result := '';
  Path := ExpandConstant('{localappdata}\ELIA\install_manifest.json');
  if not FileExists(Path) then
    Exit;
  if not LoadStringFromFile(Path, Content) then
    Exit;
  Tag := '"max_version"';
  PStart := Pos(Tag, Content);
  if PStart = 0 then
    Exit;
  PStart := PStart + Length(Tag);
  while (PStart <= Length(Content)) and (Content[PStart] <> '"') do
    PStart := PStart + 1;
  if PStart > Length(Content) then
    Exit;
  PStart := PStart + 1;
  PEnd := PStart;
  while (PEnd <= Length(Content)) and (Content[PEnd] <> '"') do
    PEnd := PEnd + 1;
  Result := Copy(Content, PStart, PEnd - PStart);
end;

function InitializeSetup: Boolean;
var
  MaxVer: String;
begin
  Result := True;
  MaxVer := ReadMaxVersionFromManifest;
  if MaxVer = '' then
    Exit;
  if CompareVersion('{#MyAppVersion}', MaxVer) < 0 then
  begin
    MsgBox(
      'Esta instalación (v{#MyAppVersion}) es anterior a la versión ya registrada en este equipo (v' +
      MaxVer + ').' + #13#10 + #13#10 +
      'No se permite instalar una versión inferior de ELIA. Usa el instalador más reciente.',
      mbError, MB_OK);
    Result := False;
  end;
end;

// Función para ejecutar comandos de permisos (solo para Windows)
procedure SetFolderPermissions(const FolderPath: string);
var
  ResultCode: Integer;
begin
  // Establecer permisos restrictivos en la carpeta core
  // Esto solo funciona en instalaciones administrativas
  if Exec(ExpandConstant('{cmd}'), '/C icacls """' + FolderPath + '""" /inheritance:r /grant:r *S-1-1-0:(RX)', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    // Permisos configurados correctamente
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // Configurar permisos después de la instalación
  if CurStep = ssPostInstall then
  begin
    if IsAdminInstallMode then
      SetFolderPermissions(ExpandConstant('{app}\_internal\core'));
  end;
end;