; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ELIA"
#define MyAppVersion "0.2.4"
#define MyAppPublisher "</Sir_Alek>"
#define MyAppURL ""
#define MyAppExeName "ELIA.exe"
#define MyOutputDir "Output"
#define MySourceDir "dist\ELIA"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#MyOutputDir}
OutputBaseFilename=ELIA_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MySourceDir}\ELIA.exe"; DestDir: "{app}"; Flags: ignoreversion
; PyInstaller 6+ coloca dependencias en _internal\ (core\, frontend\, resources\, etc.).
Source: "{#MySourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{cmd}"; Parameters: "/C taskkill /f /im ELIA.exe 2>nul"; Flags: runhidden

[Code]
// Función para ejecutar comandos de permisos (solo para Windows)
procedure SetFolderPermissions(const FolderPath: string);
var
  ResultCode: Integer;
begin
  // Establecer permisos restrictivos en la carpeta core
  // Esto solo funciona en instalaciones administrativas
  if Exec(ExpandConstant('{cmd}'), '/C icacls """' + FolderPath + '""" /inheritance:r /grant:r *S-1-1-0:(RX)', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    // Permisos configurados correctamente
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // Configurar permisos después de la instalación
  if CurStep = ssPostInstall then
  begin
    // Solo intentar configurar permisos si se está instalando para todos los usuarios
    if IsAdminInstallMode then
    begin
      SetFolderPermissions(ExpandConstant('{app}\_internal\core'));
    end;
  end;
end;